### ISSUE TITLE
0.168.192.in-addr.arpa  and 1.168.192.in-addr.arpa are in the hostnames.dead list

### ISSUE THREAD

**Issue by Homas** [notracking/hosts-blocklists-scripts#5]
Reverse DNS zones are listed in the hostnames.dead list:
0.168.192.in-addr.arpa
1.168.192.in-addr.arpa

**Comment by notracking** [comment]
These should not be in any blocklist, but apparently they have been listed somewhere (dandelionsprout malware list). Since these have no valid whois info, they will be added to this list to ensure that they are filtered out in our main blocklists.

I agree that it's not a dead domain, but as a side effect these type of invalid domains also enter up in here. This works in our advantage :)

**Comment by notracking** [comment]
I will add a fixed filter for 'in-addr.arpa' in the optimizer, that will remove these entries all together. Over time they will then also automatically removed from this list, will close this as soon as it's implemented.

Thanks for the feedback!

**Comment by Homas** [comment]
It's a "technical" domain/TLD. A similar domain exist for IPv6 - "IP6.ARPA", please add it to he optimizer as well.

https://tools.ietf.org/html/rfc1035
https://tools.ietf.org/html/rfc3596#page-3
https://tools.ietf.org/html/rfc5855
```
3.5. IN-ADDR.ARPA domain

The Internet uses a special domain to support gateway location and
Internet address to host mapping.  Other classes may employ a similar
strategy in other domains.  The intent of this domain is to provide a
guaranteed method to perform host address to host name mapping, and to
facilitate queries to locate all gateways on a particular network in the
Internet.
```

**Comment by notracking** [comment]
Fixed! Changes will be visible within a day or 2.
